name: getx_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.3.0
  loading_overlay: ^0.3.0
  flutter_svg: ^2.0.7


  get: 4.6.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - assets/icons/
    - android/app/build.gradle
    - ios/Runner.xcworkspace/xcshareddata/
    - ios/Runner.xcworkspace/


